spring.application.name: business

spring:
  config:
    import: "configserver:http://localhost:8888"

  profiles:
    active: dev

#management:
#  endpoint:
#    web:
#      exposure:
#        include:"*"

