spring.application.name: identity

spring:
  profiles:
    active: dev

  config:
    import: configserver:http://localhost:8888

logging:
  level:
    org:
      springframework:
        security: DEBUG