spring.application.name : Config-Server

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations:
          - file:///Users/vuthsarandy/Documents/CSTAD/SPRING-MS/config/service/{application}
          - file:///Users/vuthsarandy/Documents/CSTAD/SPRING-MS/config/

server:
  port: 8888
