spring.application.name : Config-Server

spring:
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/VuthSarandy/yelp-micro-istad-config.git
          search-paths: '/service/**'
          default-label: master
#        native:
#          search-locations:
#          - file:///Users/vuthsarandy/Documents/CSTAD/SPRING-MS/config/service/{application}
#          - file:///Users/vuthsarandy/Documents/CSTAD/SPRING-MS/config/

server:
  port: 8888
